disableFastRender = true
theme = ["roman", "hugo-cite"]
[frontmatter]
date = [":filename", ":default"]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 3

[[menu.main]]
identifier = "index"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "visualization"
name = "Visualization"
url = "/visualization"
weight = 2

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]
[permalinks]
pages = "/:filename"
posts = "/:filename"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
tag = "tags"

[params.cite]
  bibfile = "data/modified_bibliography.json"